# SPDX-License-Identifier: MIT
# Copyright: 2024-2026 Communauté Les Frères Poulain, NiceBots.xyz

from datetime import datetime
from enum import StrEnum
from uuid import UUID

from tortoise import fields
from tortoise.models import Model

from .guild import Guild


class StaffQuotaMode(StrEnum):
    ANY = "any"
    ALL = "all"


class StaffStatsSettings(Model):
    id: fields.Field[UUID] = fields.UUIDField(pk=True)
    guild: fields.OneToOneRelation[Guild] = fields.OneToOneField("models.Guild", related_name="staff_stats_settings")
    guild_id: int  # column generated by the relation above

    responsible_role_id: fields.Field[int | None] = fields.BigIntField(null=True)  # pyright: ignore[reportAssignmentType]
    report_channel_id: fields.Field[int | None] = fields.BigIntField(null=True)  # pyright: ignore[reportAssignmentType]

    message_channel_ids: fields.Field[list[int]] = fields.JSONField(default=list)
    voice_channel_ids: fields.Field[list[int]] = fields.JSONField(default=list)

    # Applies to every ALL ("ET") quota: a shortfall on one side can be made up on the other side,
    # at this extra cost. See quota_score() in the stats_staff extension.
    et_substitution_penalty: fields.Field[float] = fields.FloatField(default=1.25)


class StaffRoleQuota(Model):
    id: fields.Field[UUID] = fields.UUIDField(pk=True)
    guild: fields.ForeignKeyRelation[Guild] = fields.ForeignKeyField("models.Guild", related_name="staff_role_quotas")
    guild_id: int

    role_id: fields.Field[int] = fields.BigIntField()
    voice_minutes_required: fields.Field[int] = fields.IntField()
    messages_required: fields.Field[int] = fields.IntField()
    mode: StaffQuotaMode = fields.CharEnumField(enum_type=StaffQuotaMode)

    class Meta(Model.Meta):
        unique_together: tuple[tuple[str, ...], ...] = (("guild", "role_id"),)


class StaffMemberRoleOverride(Model):
    """Pins a member holding several quota roles to the one that applies to them."""

    id: fields.Field[UUID] = fields.UUIDField(pk=True)
    guild: fields.ForeignKeyRelation[Guild] = fields.ForeignKeyField(
        "models.Guild", related_name="staff_member_role_overrides"
    )
    guild_id: int

    member_id: fields.Field[int] = fields.BigIntField()
    role_id: fields.Field[int] = fields.BigIntField()

    class Meta(Model.Meta):
        unique_together: tuple[tuple[str, ...], ...] = (("guild", "member_id"),)


class StaffMessageEvent(Model):
    id: fields.Field[UUID] = fields.UUIDField(pk=True)
    guild: fields.ForeignKeyRelation[Guild] = fields.ForeignKeyField("models.Guild", related_name="staff_messages")
    guild_id: int

    member_id: fields.Field[int] = fields.BigIntField()
    channel_id: fields.Field[int] = fields.BigIntField()
    created_at: fields.Field[datetime] = fields.DatetimeField()

    class Meta(Model.Meta):
        indexes: tuple[tuple[str, ...], ...] = (("guild", "member_id", "created_at"),)


class StaffVoiceSession(Model):
    """One continuous stretch of counted voice time, in one channel.

    The id is generated in memory when the session starts, so every flush can upsert the same row.
    `ended_at` is deliberately left out of every index: it is rewritten on each flush.
    """

    id: fields.Field[UUID] = fields.UUIDField(pk=True)
    guild: fields.ForeignKeyRelation[Guild] = fields.ForeignKeyField(
        "models.Guild", related_name="staff_voice_sessions"
    )
    guild_id: int

    member_id: fields.Field[int] = fields.BigIntField()
    channel_id: fields.Field[int] = fields.BigIntField()
    started_at: fields.Field[datetime] = fields.DatetimeField()
    ended_at: fields.Field[datetime] = fields.DatetimeField()

    class Meta(Model.Meta):
        indexes: tuple[tuple[str, ...], ...] = (("guild", "member_id", "started_at"),)


__all__ = (
    "StaffMemberRoleOverride",
    "StaffMessageEvent",
    "StaffQuotaMode",
    "StaffRoleQuota",
    "StaffStatsSettings",
    "StaffVoiceSession",
)
